config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :lectures do
    resources :requests
  end
  resources :requests
  resources :subjects do
    resources :lectures
  end
  # resources :users
  get "/users",to: "users#index"
  devise_for :users,controllers: {
    sessions:"users/sessions"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "homes#index"

  resources :questions
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/lecture.rb
class Lecture < ApplicationRecord

  validates :title, presence: true
  validates :lecture_end, presence: true
  validates :lecture_start, presence: true

  belongs_to :subject
  has_many :requests

  # belongs_to :request
  has_many :requests

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: %i[ show edit update destroy ]
  before_action :check_admin?,except: [:index,:show]
  # GET /lectures or /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1 or /lectures/1.json
  def show
    @current_lectures = Lecture.where(subject_id: params[:id])
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures or /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to lecture_url(@lecture), notice: "Lecture was successfully created." }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1 or /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to lecture_url(@lecture), notice: "Lecture was successfully updated." }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1 or /lectures/1.json
  def destroy
    @lecture.destroy

    respond_to do |format|
      format.html { redirect_to lectures_url, notice: "Lecture was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
        @lecture = Lecture.find_by(id: params[:id])
        unless @lecture
          flash[:notice] = "Lecture not found"
          redirect_to root_path # Redirect to the root path or an error page
        end

    end

    # Only allow a list of trusted parameters through.
    def lecture_params
      params.require(:lecture).permit(:title, :lecture_start, :lecture_end, :subject_id)
    end
  def check_admin?
    unless current_user.admin?
      flash[:notice] = "you need admin`s user"
      redirect_to root_path
    end
  end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: lecture) do |form| %>
  <% if lecture.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
        <% lecture.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :subject_id, style: "display: block" %>
    <%= form.text_field :subject_id %>
  </div>

  <div>
    <%= form.label :lecture_start, style: "display: block" %>
    <%= form.datetime_field :lecture_start %>
  </div>

  <div>
    <%= form.label :lecture_end, style: "display: block" %>
    <%= form.datetime_field :lecture_end %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/lectures/_lecture.html.erb
<div>
  <p>
    <strong>Title:</strong>
    <%= lecture.title %>
  </p>

  <p>
    <strong>Lecture start:</strong>
    <%= lecture.lecture_start %>
  </p>

  <p>
    <strong>Lecture end:</strong>
    <%= lecture.lecture_end %>
  </p>


</div>

app/views/lectures/edit.html.erb
<h1>Editing lecture</h1>

<%= render "form", lecture: @lecture %>

<br>

<div>
  <%= link_to "Show this lecture", @lecture %> |
  <%= link_to "Back to lectures", lectures_path %>
</div>

app/views/lectures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lecturers</h1>

<div id="lectures">
  <% @lectures.each do |lecture| %>
    <%= render "lecture",lecture: lecture %>
    <p>
      <%#= link_to "Show this lecture", lecture %>
      <% user_signed_in? && if !current_user.admin? %>
        <%= link_to "make a request",new_lecture_request_path(lecture.id)%>
      <% end  %>
    </p>
    -----
  <% end %>
</div>

<%= link_to "New lecture", new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New lecture</h1>

<%= render "form", lecture: @lecture %>

<br>

<div>
  <%= link_to "Back to lectures", lectures_path %>
</div>

app/views/lectures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @current_lectures %>

<div>
  <%= link_to "Edit this lecture", edit_lecture_path(@lecture) %> |
  <%= link_to "Back to lectures", lectures_path %>

  <%= button_to "Destroy this lecture", @lecture, method: :delete %>
</div>