config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :lectures do
    resources :requests
  end
  resources :requests
  resources :subjects do
    resources :lectures
  end
  # resources :users
  get "/users",to: "users#index"
  devise_for :users,controllers: {
    sessions:"users/sessions"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "homes#index"

  resources :questions
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/request.rb
class Request < ApplicationRecord
  # validates
  belongs_to :subject
  has_many :subjects

  belongs_to :lecture
  has_many :lectures
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :check_admin?,only: [:new,:create,:index]

  def new
    @lecturer = Lecture.find(params[:lecture_id])
    @subjects = Subject.all
    @request = Request.new
  end
  def show
    @requests = Request.where(client_id: current_user.id)
    if params[:subject].present?
      subject_id = Subject.find_by(title: params[:subject])&.id
      if subject_id
        @requests = @requests.where(subject_id: subject_id)
      end
    end

  end
  def index
    @requests = Request.all
  end
  def create
    @lecturer = Lecture.find(params[:lecture_id])
    @params = params.require(:request).permit(:lecture_start,:lecture_end)

    p ">>>>>>>>>>>>>>>>>>>"
    p @params[:lecture_start]

    @request = Request.new(
      request_code: rand(10000000000),
      date: @params[:lecture_start].to_s + " - " + @params[:lecture_end].to_s,
      client_id: current_user.id,
      subject_id: @lecturer.subject_id,
      lecturer_id: params[:lecture_id],
      lecture_start: @params[:lecture_start],
      lecture_end: @params[:lecture_end],
      actual_lecture_hours: @lecturer.lecture_start.to_s + @lecturer.lecture_end.to_s
    )
    if @request.save
      flash[:notice] = "request saved"
      redirect_to root_path
    end
  end

  def check_admin?
    unless current_user.admin?
      flash[:notice] = "admin user can not make request"
      redirect_to root_path
    end
  end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/index.html.erb
<% @requests.each do |request| %>
  <p>
    <strong>Code: </strong>
    <%= request[:request_code] %>
  </p>

  <p>
    <strong>subject: </strong>
    <% sub = Subject.find_by(id: request.lecturer_id)  %>
    <%= sub.title %>
  </p>
  <p>
    <strong>date: </strong>
    <%= request[:date] %>
  </p>

  <p>
    <strong>lecturer: </strong>
    <% lect = Lecture.find_by(id: request.lecturer_id)  %>
    <%= lect.title %>
  </p>
  <p>
    <strong>lecture_start: </strong>
    <%= request[:lecture_start] %>
  </p>
  <p>
    <strong>lecture_end: </strong>
    <%= request[:lecture_end] %>
  </p>
  <p>
    <strong>actual lecture hours: </strong>
    <%= request[:actual_lecture_hours] %>
  </p>
  -------
<% end %>

app/views/requests/new.html.erb
<%= form_with model: @request,url: lecture_requests_path(@lecturer) do |f| %>

  <%= f.datetime_field :lecture_start %>
  <%= f.datetime_field :lecture_end %>

  <%= f.submit %>

<% end %>

app/views/requests/show.html.erb
<%= flash[:notice] %>

<h1>My requests</h1>

<%= form_with(url: request_path(params[:id]), method: :get) do |form| %>
  <%= form.label :subject %>
  <%= form.select :subject, options_for_select(Subject.pluck(:title),params[:subject]), include_blank: true %>
  <%= form.submit "Filter" %>
<% end %>


<% @requests.each do |request| %>
    <p>
      <strong>Code: </strong>
      <%= request[:request_code] %>
    </p>

  <p>
    <strong>subject: </strong>
    <% sub = Subject.find_by(id: request.lecturer_id)  %>
    <%= sub.title %>
  </p>
  <p>
    <strong>date: </strong>
    <%= request[:date] %>
  </p>

  <p>
    <strong>lecturer: </strong>
    <% lect = Lecture.find_by(id: request.lecturer_id)  %>
    <%= lect.title %>
  </p>
  <p>
    <strong>lecture_start: </strong>
    <%= request[:lecture_start] %>
  </p>
  <p>
    <strong>lecture_end: </strong>
    <%= request[:lecture_end] %>
  </p>
  <p>
    <strong>actual lecture hours: </strong>
    <%= request[:actual_lecture_hours] %>
  </p>
-------
<% end %>