config/routes.rb
Rails.application.routes.draw do
  resources :subjects
  resources :lectures do
    resources :requests
  end
  resources :requests
  resources :subjects do
    resources :lectures
  end
  # resources :users
  get "/users",to: "users#index"
  devise_for :users,controllers: {
    sessions:"users/sessions"
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root to: "homes#index"

  resources :questions
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :lectures

  has_many :requests
  belongs_to :request

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: %i[ show edit update destroy ]
  before_action :check_admin?,except: [:index]
  # GET /subjects or /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1 or /subjects/1.json
  def show
  end
  def my

  end
  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects or /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully created." }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1 or /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to subject_url(@subject), notice: "Subject was successfully updated." }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1 or /subjects/1.json
  def destroy
    @subject.destroy

    respond_to do |format|
      format.html { redirect_to subjects_url, notice: "Subject was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subject_params
      params.require(:subject).permit(:title, :description)
    end
  def check_admin?
    unless current_user.admin?
      flash[:notice] = "you need admin`s user"
      redirect_to root_path
    end
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject) do |form| %>
  <% if subject.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
        <% subject.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/_subject.html.erb
<div>
  <p>
    <strong>Title:</strong>
    <%= subject.title %>
  </p>

  <p>
    <strong>ID:</strong>
    <%= subject.id %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= subject.description %>
  </p>


</div>

app/views/subjects/edit.html.erb
<h1>Editing subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Show this subject", @subject %> |
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subjects</h1>

<div id="subjects">
  <% @subjects.each do |subject| %>
    <%= render subject %>
    <p>
      <%= link_to "Show this subject", subject %>
      <%= link_to "show lectures",lecture_path(subject.id) %>
    </p>
  <% end %>
</div>

<%= link_to "New subject", new_subject_path %>

app/views/subjects/new.html.erb
<h1>New subject</h1>

<%= render "form", subject: @subject %>

<br>

<div>
  <%= link_to "Back to subjects", subjects_path %>
</div>

app/views/subjects/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subject %>

<div>
  <%= link_to "Edit this subject", edit_subject_path(@subject) %> |
  <%= link_to "Back to subjects", subjects_path %>

  <%= button_to "Destroy this subject", @subject, method: :delete %>
</div>